### ISSUE TITLE
[FEATURE] Make thrown exceptions consistent type

### ISSUE THREAD

**Issue by zkingston** [KavrakiLab/robowflex#206]
Currently a few exceptions are a thrown in the code that aren't the defined `robowflex::Exception` type, such as `std::runtime_error`. This should be made consistent.

**Comment by ChamzasKonstantinos** [comment]
The result of grep -rini in top robowflex library:

src/io/hdf5.cpp:101:        throw std::invalid_argument("Index size must be the same as data rank!");
src/geometry.cpp:30:        throw Exception(1, "Invalid type for geometry.");
src/geometry.cpp:38:        throw Exception(1, "Invalid type for geometry.");
src/geometry.cpp:151:            throw Exception(1, "Invalid type for geometry.");
src/geometry.cpp:191:                throw Exception(1, resource_.empty() ? "No vertices/resource specified for the mesh" :
src/io.cpp:417:                    throw Exception(1, "Unknown non-scalar node type in YAML");
src/io.cpp:462:        throw Exception(1, "Unknown node value in YAML");
src/io.cpp:501:            throw Exception(1, "Unknown node type in YAML");
src/scene.cpp:471:    throw std::runtime_error("Not Implemented");
src/scene.cpp:514:    throw std::runtime_error("Not Implemented");
src/builder.cpp:81:        throw std::runtime_error("Invalid planner!");
src/builder.cpp:101:        throw std::runtime_error("Invalid joint group name!");
src/builder.cpp:162:        throw std::runtime_error("No planning group set!");
src/builder.cpp:212:        throw std::runtime_error("No planning group set!");
src/builder.cpp:229:        throw std::runtime_error("No planning group set!");
src/builder.cpp:241:        throw std::runtime_error("No planning group set!");
src/builder.cpp:247:        throw std::runtime_error("Mismatched query groups!");
src/builder.cpp:253:        throw std::runtime_error("Tried to set goal from multi-target request!");
src/builder.cpp:263:            throw std::runtime_error("Unable to find tip frame for request.");
src/builder.cpp:273:        throw std::runtime_error("Unable to find base frame for request.");
src/robot.cpp:635:        throw std::runtime_error("Invalid multi-target IK query. poses != tips.");
src/trajectory.cpp:148:    throw std::runtime_error("Not Implemented");
include/robowflex_library/util.h:39:        virtual const char *what() const throw()
