### ISSUE TITLE
OMPL::OMPLInterfacePlanner cannot set the config files 

### ISSUE THREAD

**Issue by ChamzasKonstantinos** [KavrakiLab/robowflex#21]
I get the warning 
``` Cannot find planning configuration for group 'arm_with_torso' using planner 'PRMkConfigDefault'. Will use defaults instead. ```  the exact same command works with FetchOMPLPipeline

**Comment by BryceStevenWilley** [comment]
Can recreate, it seems that the joint groups are not being loaded correctly, as this same error comes up using RRTConnect and for the `arm` group as well. 

Looking into it, this should happen in `ompl_interface::OMPLInterface` object, in [loadPlannerConifigurations()](https://github.com/ros-planning/moveit/blob/kinetic-devel/moveit_planners/ompl/ompl_interface/src/ompl_interface.cpp#L268), but I guess this isn't working.
