### ISSUE TITLE
Robot::initialize is ambigious when initialized with two parameters

### ISSUE THREAD

**Issue by werner291** [KavrakiLab/robowflex#228]
Hello!

See the methods:

- `Robot::initialize(const std::string &urdf_file, const std::string &srdf_file);`
- `initialize(const std::string &urdf_file, const std::string &srdf_file,
                        const std::string &limits_file = "", const std::string &kinematics_file = "")`

When called like this:
`drone->initialize(
            "package://drone_moveit_config/urdf/bot.urdf",
            "package://drone_moveit_config/config/aerial_manipulator_drone.srdf"
            );`

I get the error:
```
/home/werner/catkin_ws/src/robowflex/robowflex_library/include/robowflex_library/robot.h:109:14: note: candidate: ‘bool robowflex::Robot::initialize(const string&, const string&)’
  109 |         bool initialize(const std::string &urdf_file, const std::string &srdf_file);
      |              ^~~~~~~~~~
/home/werner/catkin_ws/src/robowflex/robowflex_library/include/robowflex_library/robot.h:125:14: note: candidate: ‘bool robowflex::Robot::initialize(const string&, const string&, const string&, const string&)’
  125 |         bool initialize(const std::string &urdf_file, const std::string &srdf_file,
```

I think this is caused by the compiler being unable to distinguish beteen calling the method with two parameters, or the one with four parameters where the last two are filled with the empty-string default.

**Comment by werner291** [comment]
https://github.com/KavrakiLab/robowflex/blob/master/robowflex_library/src/robot.cpp#L199

As far as I can tell, one just calls the other. Perhaps you could just drop the one with two parameters?

**Comment by ChamzasKonstantinos** [comment]
Thanks for reporting this!
