### ISSUE TITLE
[BUG] Segfault when attempting to benchmark some planners

### ISSUE THREAD

**Issue by werner291** [KavrakiLab/robowflex#239]
Hello, I'm trying to run a benchmark of a few planners for a quadcopter with an aerial manipulator, though I ran into some kind of segfault when the benchmark code tries to clear the state between runs.

## Expected Behavior

The benchmark completes and results are output.

## Current Behavior

I get a segfault, with the following stack trace in the debugger:

```
__GI___libc_free 0x00007f1871088870
ompl_interface::ModelBasedStateSpace::freeState 0x00007f1870f86c86
ompl::geometric::RRT::freeMemory() 0x00007f1870c91faa
ompl::geometric::RRT::clear() 0x00007f1870c92078
ompl::geometric::SimpleSetup::clear() 0x00007f1870d48997
ompl_interface::ModelBasedPlanningContext::clear 0x00007f1870f71373
ompl_interface::PlanningContextManager::getPlanningContext 0x00007f1870f4eb6c
ompl_interface::OMPLInterface::getPlanningContext 0x00007f1870f3ac59
ompl_interface::OMPLInterface::getPlanningContext 0x00007f1870f3accf
robowflex::OMPL::OMPLInterfacePlanner::getPlanningContext(std::shared_ptr<robowflex::Scene const> const&, moveit_msgs::MotionPlanRequest_<std::allocator<void> > const&) const 0x00007f187185fbc7
robowflex::OMPL::OMPLInterfacePlanner::refreshContext(std::shared_ptr<robowflex::Scene const> const&, moveit_msgs::MotionPlanRequest_<std::allocator<void> > const&, bool) const 0x00007f187185fefd
robowflex::Experiment::benchmark(unsigned long) const::{lambda()#1}::operator()() const 0x00007f187170acd4
<unknown> 0x00007f187141fde4
start_thread 0x00007f186ffec609
clone 0x00007f187110d293
```

## Possible Solution

I imagine there's a state being deleted that should not be deleted somewhere.

## Steps to Reproduce

This is the code, I tried to narrow it down as much as I could. Appears to be specific to this robot as well:

[run_benchmark.cpp.txt](https://github.com/KavrakiLab/robowflex/files/6944806/run_benchmark.cpp.txt)
[bot.urdf.txt](https://github.com/KavrakiLab/robowflex/files/6944809/bot.urdf.txt)
[aerial_manipulator_drone.srdf.txt](https://github.com/KavrakiLab/robowflex/files/6944812/aerial_manipulator_drone.srdf.txt)
[ompl_planning.yaml.txt](https://github.com/KavrakiLab/robowflex/files/6944880/ompl_planning.yaml.txt)

(suffixed with a .txt filename extension because GitHub won't accept the files otherwise)

Segfault typically occurs after an inconsistent number of trials: sometimes after a couple, sometimes a dozen or so succeed.

## Context (Environment)

I'm on ROS Noetic, on Ubuntu 20.04 LTS.

Bowflex is version https://github.com/KavrakiLab/robowflex/pull/238/commits/becd8fe47d73a230b095aaaaea7cb5ec066bd718 (the pull request), but latest master probably works too.

**Comment by werner291** [comment]
Doesn't appear to occur when just running the planner like this:

```
    for (int i = 0; i < 000; i++) {

        auto request = std::make_shared<MotionRequestBuilder>(simple_planner, "whole_body");

        request->setConfig("RRT");
        request->setWorkspaceBounds(
                Eigen::Vector3d(-20.0, -20.0, -20.0),
                Eigen::Vector3d(20.0, 20.0, 20.0)
                );

        request->setStartConfiguration({-10.0,-10.0,10.0, 0.0,0.0,0.0,1.0, 0.5});
        request->setGoalConfiguration({10.0,10.0,10.0, 0.0,0.0,0.0,1.0, 0.5});

        planning_interface::MotionPlanResponse res = simple_planner->plan(scene, request->getRequest());

    }
```

**Comment by werner291** [comment]
Ok, might not be necessarily related to benchmarking, this code does it too:

```
    for (int i = 0; i < 100; i++) {

        auto request = std::make_shared<MotionRequestBuilder>(simple_planner, "whole_body");

        request->setConfig("RRT");
        request->setWorkspaceBounds(
                Eigen::Vector3d(-20.0, -20.0, -20.0),
                Eigen::Vector3d(20.0, 20.0, 20.0)
                );

        request->setStartConfiguration({-10.0,-10.0,10.0, 0.0,0.0,0.0,1.0, 0.5});
        request->setGoalConfiguration({10.0,10.0,10.0, 0.0,0.0,0.0,1.0, 0.5});

        planning_interface::MotionPlanResponse res = simple_planner->plan(scene, request->getRequest());

    }
```

**Comment by werner291** [comment]
Seems to be tied to RRT somehow, suspecting it performs a double-free somehow.

**Comment by werner291** [comment]
```
[ WARN] [1628251127.060703981]: Computed solution is approximate
Signal: SIGSEGV (Segmentation fault)
```

Not sure, but I'm getting the impression it's somehow tied to there being an approximate solution or not...

**Comment by werner291** [comment]
This is getting weirder by the minute... Somethimes the segfault goes away, then I clean the build, and it'll be back.

**Comment by werner291** [comment]
When using TRRT exclusively, the error output seems to consistently look like this:

```
[ INFO] [1628261769.638698794]: Unable to solve the planning problem
[ INFO] [1628261769.638718184]: Reusing Cached Context!
[ INFO] [1628261769.640492496]: Shutting down with signal Segmentation fault.
[ WARN] [1628261769.638664054]: Computed solution is approximate
```

Apparently, it has to do with the planner failing somehow,

**Comment by zkingston** [comment]
I'm taking a look at this now. It seems that the issues might (?) lie somewhere in the internals of the OMPL planner - I'm seeing multiple copies of the same pointer inside RRT's nearest neighbor structure that are getting double freed.

**Comment by zkingston** [comment]
There appears to be some sort of strange race condition that I can't quite pin down. If you use the pipeline planner (rather than the OMPL Interface planner) this problem does not seem to appear. I'll have some more time to look into this later.

**Comment by zkingston** [comment]
To elaborate: the problematic behavior that appears that causes this issue is in the distance function of MoveIt's state space. It reports that two identical states have a non-zero distance, which in turn breaks the goal satisfaction check inside the motion planner, which leads to many copies of identical states being added to the nearest neighbor structure, which causes weird duplication issues. I'm not sure what causes the distance function to have this error - if you add a print statement in the JointModelGroup::distance() function in MoveIt, the issues disappears.

**Comment by werner291** [comment]
Might it have something to do with the fact that the robot has a floating/free joint as its' virtual joint?

So far, I've noticed that MoveIt _really_ doesn't seem to like that, apparently significant parts of it were written with kinematic chains with 1-DoF joints in mind. Perhaps there's a bug in comparing distances between higher-DoF joints?

**Comment by zkingston** [comment]
A little more testing later: if you simply comment out `settings.max_goal_samples = 1` and allow the default settings, everything works. It appears that there is some deep bug with specific goal samples when you have tight tolerances near the boundary of the state space in MoveIt - I don't really have the time to investigate this further, but that is an operational fix.

**Comment by werner291** [comment]
Allright, I'll try it with the higher number of goal samples; I suppose that whatever happens then becomes so unlikely as to basically become practically impossible. I'm probably still going to poke around MoveIt's source code to see if I can find something, but it does sound out-of-scope for `robowflex`.

Thanks for the help anyway!

**Comment by werner291** [comment]
@zkingston Can you maybe post a few links to pointers in the source code where you think the issue might be? You said MoveIt's distance function?

**Comment by werner291** [comment]
world_joint = 10 10 10 6.97303e-17 -3.27952e-17 -7.03514e-17 1 

That ain't a valid unit quaternion... And I'm guessing that this is somehow _just_ bigger than the epsilon value being used in the equality comparison. Seems that goal sampling is to blame.

To be expected... MoveIt really doesn't like floating joints.

I'll check the goal sampler to see where this is coming from...

**Comment by werner291** [comment]
Yep, that's it, the quaternion in the floating joint is getting corrupted. The zero-values in the quaternion are consistently non-zero (but tiny). Then there's a goal sample where it's slightly bigger, and we near-immediately get a crash!

**Comment by werner291** [comment]
Oh, look what the default planning pipeline does: https://github.com/ros-planning/moveit/blob/779b7c8b019f70898d4de3189f9261c9697d9b9f/moveit_ros/planning/planning_request_adapter_plugins/src/fix_start_state_bounds.cpp#L133

**Comment by werner291** [comment]
I think I found the root cause: https://github.com/ros-planning/moveit/blob/master/moveit_core/constraint_samplers/src/default_constraint_samplers.cpp#L89

Apparently, joint constraints have a "tolerance", which is some kind of small epsilon value that widens the sampling range a little bit, allowing for the sampling of invalid quaternions (and probably other joint types).

**Comment by werner291** [comment]
Since the root cause is now known, but it's still unclear whether there's a valid reason for adding those tolerances to the sampling range, maybe reopen this issue until the crash goes away?

**Comment by zkingston** [comment]
I'll look into possibly adding the planning pipeline adapter interface to the OMPL interface planner - nice work figuring this one out.
