### ISSUE TITLE
[BUG] Segfault when loading SRDF due to upstream issue

### ISSUE THREAD

**Issue by werner291** [KavrakiLab/robowflex#240]
Again, another heads-up, since I think my PR (https://github.com/ros-planning/moveit/pull/2806) fixes it, but robots that have SRDF fail to load with latest MoveIt master branch at the time of writing.

Given the overall instability of the ROS ecosystem, maybe it's a good idea to just keep an open issue and add comments to it when things like these come in? opening a full issue feels a bit much, but documenting these things in case someone runs into them might be a good idea too.

**Comment by zkingston** [comment]
Sounds like a good idea, I'll close this issue and open up a "meta issue" with the problems found in MoveIt so far.
