### ISSUE TITLE
setGoalConfiguration() is misleading

### ISSUE THREAD

**Issue by ChamzasKonstantinos** [KavrakiLab/robowflex#251]
The [setGoalConfiguration()](https://kavrakilab.github.io/robowflex/classrobowflex_1_1MotionRequestBuilder.html#a7ec31a3b72b88a9ee906c6a477eec377) function is  misleading since it adds a Goal-configuration to the existing set of goals. 

I think we should rename this function to addGoalConfiguration() and, the setGoalConfiguration will call clearGoals and then 
setGoalConfiguration()

If @zkingston  you agree I can make PR.

**Comment by zkingston** [comment]
Sure, I agree with this.

**Comment by zkingston** [comment]
Closed by #252
