### ISSUE TITLE
UniformInt does has wrong range [BUG]

### ISSUE THREAD

**Issue by ChamzasKonstantinos** [KavrakiLab/robowflex#294]
function [RandomInt() ](https://github.com/KavrakiLab/robowflex/blob/master/robowflex_library/src/random.cpp#L34)returns a value in [lower_bound, upper_bound] instead of  [lower_bound, upper_bound) as mentioned [here](https://kavrakilab.github.io/robowflex/namespacerobowflex_1_1RNG.html#aaa1fda5137839d2555722cd3a5ebe3dd). 

It's an easy fix, but the question is, do we fix the documentation or the function?
I propose the function since it works better with vector indexing.

**Comment by zkingston** [comment]
Sure, we should fix the function to return in the [) interval rather than [].
