### ISSUE TITLE
Issues linking to Curl openssl 4

### ISSUE THREAD

**Issue by th3rring** [KavrakiLab/robowflex#31]
Not sure, but in installing Robowflex with Kavrakilab Env on my personal machine, we ran into issues linking curl against resource retriever.

Zak got this working by manually adding -lcurl

Error output:
[error.txt](https://github.com/KavrakiLab/robowflex/files/2358687/error.txt)

**Comment by juandhv** [comment]
but is this issue specific to Melodic ? I don't any problem in Kinetic

**Comment by zkingston** [comment]
I'll note that I've never had this problem before with building on Melodic.

Another interesting tidbit was that `ldd libresource-retriever.so` (the offending `.so` which complains about not finding `libcurl` functions) did in fact reference `libcurl.so.4`, and a `objdump -T libcurl.so.4` showed that the functions did exist. Running an additional `ldconfig` didn't seem to do anything...

**Comment by BryceStevenWilley** [comment]
In case y'all run into this again, there's a similar issue on moveit: https://github.com/ros-planning/moveit/issues/697

**Comment by th3rring** [comment]
Just had this on my personal machine. It seemed like there were conflicting versions of `libcurl4` installed. I had Anaconda installed which seemed to use a version that didn't use openssl. Removing Anaconda and ROS and reinstalling ROS fixed the problem.
